import { buildSimulationSummary } from '@features/simulation/engine'
import { computeAtomTotals } from '@domain/resources/resourceCatalog'
import {
  buildTutorialChecklist,
  createTutorialCompletion,
} from '@state/quests/tutorialProgression'
import {
  createEmptyInventory,
  DEFAULT_PLAYER_USERNAME,
  DEFAULT_SHIP_TELEMETRY,
  resolveInitialPinnedQuestIds,
  type StoreBootstrapContext,
} from '@state/runtime/storeBootstrap'
import type { AppState } from '@state/appStoreState'
import type { AppActionSlices } from '@state/slices/appActionSlices'

export interface BuildAppInitialStateOptions {
  bootstrap: StoreBootstrapContext
  actionSlices: AppActionSlices
}

export function buildAppInitialState(options: BuildAppInitialStateOptions): AppState {
  const {
    bootstrap,
    actionSlices,
  } = options
  const {
    defaultMarketState,
    loadedRuntimeSnapshot,
    loadedUiPreferences,
    initialActiveSectorId,
    initialWorldSeed,
    initialWorldTargetCount,
    initialDockState,
    initialHiddenPanels,
    initialPanelSlotHints,
    initialUiDensity,
    initialPanelOpacity,
    initialStationDistanceManual,
    initialStationDistanceScene,
    initialUseSceneDistance,
    initialDocked,
    initialStationDistance,
    initialContainmentPower,
    initialCharging,
    initialContainmentOn,
    initialCycleTimeSeconds,
    initialCrewStatus,
    initialCrewMembers,
    initialCrewAggregateMetrics,
    initialFridge,
    initialWaterAutomationEnabled,
  } = bootstrap
  const initialInventory = createEmptyInventory()

  return {
    inventory: initialInventory,
    inventoryLoaded: false,
    atomCounter: computeAtomTotals(initialInventory),
    selectedObject: null,
    playerUsername: loadedRuntimeSnapshot.playerUsername ?? DEFAULT_PLAYER_USERNAME,
    activeCommsSpeaker: null,
    shipTelemetry: DEFAULT_SHIP_TELEMETRY,
    crewStatus: initialCrewStatus,
    crewMembers: initialCrewMembers,
    crewAggregateMetrics: initialCrewAggregateMetrics,
    fridge: initialFridge,
    waterAutomationEnabled: initialWaterAutomationEnabled,
    radarContacts: [],
    activeSectorId: initialActiveSectorId,
    worldStateLoaded: false,
    worldSeed: initialWorldSeed,
    worldDepletedTargetIds: [],
    worldDestroyedCount: 0,
    worldRemainingCount: initialWorldTargetCount,
    worldVisitedZoneIds: [],
    worldZoneDestroyedCounts: {},
    worldClassDestroyedCounts: {},
    activeCleanupZoneId: null,
    visitedCleanupZones: [],
    pinnedQuestIds: resolveInitialPinnedQuestIds(loadedUiPreferences),
    activeMainQuestId: loadedUiPreferences.activeMainQuestId ?? null,
    leftPanels: initialDockState.leftPanels,
    rightPanels: initialDockState.rightPanels,
    hiddenPanels: initialHiddenPanels,
    panelSlotHints: initialPanelSlotHints,
    uiDensity: initialUiDensity,
    panelOpacity: initialPanelOpacity,
    workspaceCustomizerOpen: false,
    stationDistance: initialStationDistance,
    stationDistanceScene: initialStationDistanceScene,
    stationDistanceManual: initialStationDistanceManual,
    useSceneDistance: initialUseSceneDistance,
    charging: initialCharging,
    docked: initialDocked,
    containmentOn: initialContainmentOn,
    containmentPower: initialContainmentPower,
    cycleTimeSeconds: initialCycleTimeSeconds,
    energy: loadedRuntimeSnapshot.energy ?? 120,
    maxEnergy: loadedRuntimeSnapshot.maxEnergy ?? 2000,
    credits: loadedRuntimeSnapshot.credits ?? 0,
    shipRespawnSignal: 0,
    failureCount: loadedRuntimeSnapshot.failureCount ?? 0,
    failureReports: [],
    starvationFailureLock: false,
    market: loadedRuntimeSnapshot.market ?? defaultMarketState,
    simulationSummary: buildSimulationSummary({
      stationDistance: initialStationDistance,
      charging: initialCharging,
      containmentOn: initialContainmentOn,
      containmentPower: initialContainmentPower,
    }),
    simulationLog: [
      {
        id: Date.now(),
        message: 'Simulation ready. Mine asteroids into rubble, then process at the station.',
        timestamp: Date.now(),
      },
    ],
    questRewardNotifications: [],
    questRewardHistory: loadedRuntimeSnapshot.questRewardHistory ?? [],
    extractionEvents: [],
    crewFeedsDelivered: loadedRuntimeSnapshot.crewFeedsDelivered ?? 0,
    claimedQuestRewardIds: loadedRuntimeSnapshot.claimedQuestRewardIds ?? [],
    tutorialEnabled: true,
    tutorialCollapsed: false,
    tutorialComplete: false,
    tutorialCurrentStepIndex: 0,
    tutorialChecklist: buildTutorialChecklist(createTutorialCompletion()),
    tutorialCompletion: createTutorialCompletion(),
    labActiveTab: loadedRuntimeSnapshot.labActiveTab ?? 'sorting',
    hydrateWorldSession: actionSlices.worldSessionActionBindings.hydrateWorldSession,
    jumpToSector: actionSlices.worldSessionActionBindings.jumpToSector,
    hydrateInventory: actionSlices.runtimeActionBindings.hydrateInventory,
    ...actionSlices.extractionActionBindings,
    ...actionSlices.worldTargetActionBindings,
    ...actionSlices.processActionBindings,
    ...actionSlices.resourceActionBindings,
    tickSimulation: actionSlices.simulationActionBindings.tickSimulation,
    ...actionSlices.stationControlActionBindings,
    ...actionSlices.basicStateActionBindings,
    ...actionSlices.uiWorkflowActionBindings,
    resetAllProgress: actionSlices.runtimeActionBindings.resetAllProgress,
  }
}
