import { CHARGING_RANGE_METERS, CONTAINMENT_DRAIN_BASE, CONTAINMENT_DRAIN_POWER_FACTOR, CREW_AUTO_DRINK_THRESHOLD, CREW_AUTO_EAT_THRESHOLD, CREW_DEHYDRATED_THRESHOLD, CREW_DEBUFF_MAX, CREW_MEMBER_COUNT, CREW_MEMBER_DEBUFF_GAIN_DEHYDRATED_PER_SECOND, CREW_MEMBER_DEBUFF_GAIN_STARVING_PER_SECOND, CREW_MEMBER_DEBUFF_RECOVERY_PER_SECOND, CREW_MEMBER_GALAXY_BAR_HUNGER_RESTORE, CREW_MEMBER_HUNGER_DECAY_PER_SECOND, CREW_MEMBER_THIRST_DECAY_PER_SECOND, CREW_MEMBER_WATER_DRINK_COST_L, CREW_MEMBER_WATER_HYDRATION_RESTORE, CREW_SLEEP_CYCLE_HOURS, CREW_SLEEP_SHIFT_START_HOURS, CREW_SLEEP_WINDOW_HOURS, CREW_STARVING_THRESHOLD, FRIDGE_DEFAULT_CAPACITY_BARS, FRIDGE_UNLOCK_REWARD_GALAXY_BARS, MARKET_DEMAND_RECOVERY_PER_SECOND, MARKET_PRICE_CEIL_MULTIPLIER, MARKET_PRICE_FLOOR_MULTIPLIER, MARKET_PRODUCTS, MARKET_RANDOM_SWAY, MINING_ASTEROID_RUBBLE_YIELD, MINING_LASER_ENERGY_COST, RECOMBINATION_BASE_RATE, RECOMBINATION_MAX_CONTAINMENT_EFFECT, SIMULATION_TICK_ORDER, } from '../../../src/domain/spec/gameSpec.js';
import { formatQty } from '../formatters.js';
import { AUTO_GENERATED_HEADER } from '../types.js';
export function buildSystemsPage() {
    const content = [
        AUTO_GENERATED_HEADER,
        '# Systems Reference',
        '',
        'This page is generated from game constants and is always source-of-truth.',
        '',
        '## Core Simulation Constants',
        `- Charging range: **${CHARGING_RANGE_METERS} m**`,
        `- Mining laser energy cost: **${formatQty(MINING_LASER_ENERGY_COST)}**`,
        `- Asteroid rubble yield per mine: **${formatQty(MINING_ASTEROID_RUBBLE_YIELD)}**`,
        '',
        '## Tick Order',
        ...SIMULATION_TICK_ORDER.map((step, index) => `${index + 1}. \`${step}\``),
        '',
        '## Plasma + Containment',
        `- Containment drain base: **${formatQty(CONTAINMENT_DRAIN_BASE)} / sec**`,
        `- Containment drain power factor: **${formatQty(CONTAINMENT_DRAIN_POWER_FACTOR)} / sec**`,
        `- Recombination base rate: **${formatQty(RECOMBINATION_BASE_RATE * 100)}% / sec**`,
        `- Max recombination reduction from containment: **${formatQty(RECOMBINATION_MAX_CONTAINMENT_EFFECT * 100)}%**`,
        '',
        '## Crew Survival (Per Member)',
        `- Crew count: **${formatQty(CREW_MEMBER_COUNT)}**`,
        `- Hunger decay: **${formatQty(CREW_MEMBER_HUNGER_DECAY_PER_SECOND)} / sec**`,
        `- Thirst decay: **${formatQty(CREW_MEMBER_THIRST_DECAY_PER_SECOND)} / sec**`,
        `- Starving threshold: **${formatQty(CREW_STARVING_THRESHOLD)}**`,
        `- Dehydrated threshold: **${formatQty(CREW_DEHYDRATED_THRESHOLD)}**`,
        `- Auto-eat threshold: **${formatQty(CREW_AUTO_EAT_THRESHOLD)}**`,
        `- Auto-drink threshold: **${formatQty(CREW_AUTO_DRINK_THRESHOLD)}**`,
        `- Galaxy Bar hunger restore: **${formatQty(CREW_MEMBER_GALAXY_BAR_HUNGER_RESTORE)}**`,
        `- Water drink cost: **${formatQty(CREW_MEMBER_WATER_DRINK_COST_L)} L**`,
        `- Water drink restore: **${formatQty(CREW_MEMBER_WATER_HYDRATION_RESTORE)}**`,
        `- Debuff max: **${formatQty(CREW_DEBUFF_MAX)}%**`,
        `- Debuff gain (starving): **${formatQty(CREW_MEMBER_DEBUFF_GAIN_STARVING_PER_SECOND)}% / sec**`,
        `- Debuff gain (dehydrated): **${formatQty(CREW_MEMBER_DEBUFF_GAIN_DEHYDRATED_PER_SECOND)}% / sec**`,
        `- Debuff recovery (healthy): **${formatQty(CREW_MEMBER_DEBUFF_RECOVERY_PER_SECOND)}% / sec**`,
        '',
        '## Sleep Rotation',
        `- Sleep cycle: **${formatQty(CREW_SLEEP_CYCLE_HOURS)} h**`,
        `- Sleep window: **${formatQty(CREW_SLEEP_WINDOW_HOURS)} h**`,
        `- Shift starts: **${CREW_SLEEP_SHIFT_START_HOURS.join(', ')} h**`,
        '',
        '## Fridge',
        `- Default capacity: **${formatQty(FRIDGE_DEFAULT_CAPACITY_BARS)} Galaxy Bars**`,
        `- Feed The Crew unlock preload: **${formatQty(FRIDGE_UNLOCK_REWARD_GALAXY_BARS)} Galaxy Bars**`,
        '',
        '## Market Model',
        `- Demand recovery: **${formatQty(MARKET_DEMAND_RECOVERY_PER_SECOND)} / sec**`,
        `- Random sway magnitude: **${formatQty(MARKET_RANDOM_SWAY)}**`,
        `- Price floor multiplier: **${formatQty(MARKET_PRICE_FLOOR_MULTIPLIER)}x**`,
        `- Price ceiling multiplier: **${formatQty(MARKET_PRICE_CEIL_MULTIPLIER)}x**`,
        '',
        '### Tracked Products',
        ...MARKET_PRODUCTS.map((product) => `- ${product.label} (\`${product.productId}\`) base price: **${formatQty(product.basePrice)} cr**`),
        '',
    ].join('\n');
    return {
        meta: {
            slug: 'reference-systems',
            title: 'Systems Reference',
            summary: 'Generated constants for station, tick order, plasma, crew, and market behavior.',
            tags: ['reference', 'systems', 'simulation'],
        },
        filename: 'reference-systems.mdx',
        content,
    };
}
