export const TRAINING_SECTOR_ID = 'flightTraining';
export const EARTH_CORRIDOR_SECTOR_ID = 'earthCorridor';
export const MARS_CORRIDOR_SECTOR_ID = 'marsCorridor';
export const DEFAULT_START_SECTOR_ID = TRAINING_SECTOR_ID;
const trainingOrbitZones = [
    {
        id: 'nearStationBelt',
        label: 'Training Perimeter',
        description: 'Quiet low-traffic perimeter reserved for basic flight drills.',
        center: { x: 0, y: 0, z: 0 },
        radius: 180,
        targetCount: 0,
        riskRating: 0.1,
        classWeights: {
            rockBody: 1,
            metalScrap: 0,
            compositeJunk: 0,
            carbonRichAsteroid: 0,
            volatileIceChunk: 0,
        },
    },
    {
        id: 'denseDebrisLane',
        label: 'Training Drift Lane',
        description: 'Empty drift lane used for strafing and boost control checks.',
        center: { x: 180, y: 24, z: -140 },
        radius: 160,
        targetCount: 0,
        riskRating: 0.1,
        classWeights: {
            rockBody: 1,
            metalScrap: 0,
            compositeJunk: 0,
            carbonRichAsteroid: 0,
            volatileIceChunk: 0,
        },
    },
    {
        id: 'highRiskSalvagePocket',
        label: 'Training Outer Pocket',
        description: 'Wide open pocket used to practice target tracking and laser firing.',
        center: { x: -220, y: -30, z: 180 },
        radius: 170,
        targetCount: 0,
        riskRating: 0.1,
        classWeights: {
            rockBody: 1,
            metalScrap: 0,
            compositeJunk: 0,
            carbonRichAsteroid: 0,
            volatileIceChunk: 0,
        },
    },
];
const earthCorridorZones = [
    {
        id: 'nearStationBelt',
        label: 'LEO Cleanup Ring',
        description: 'Low Earth orbit cleanup lane near station approaches.',
        center: { x: 0, y: 0, z: 0 },
        radius: 260,
        targetCount: 16,
        riskRating: 0.34,
        classWeights: {
            rockBody: 0.18,
            metalScrap: 0.22,
            compositeJunk: 0.34,
            carbonRichAsteroid: 0.1,
            volatileIceChunk: 0.16,
        },
    },
    {
        id: 'denseDebrisLane',
        label: 'Landfill Drift Belt',
        description: 'Dense man-made drift lane with mixed Earth-side debris.',
        center: { x: 220, y: 28, z: -150 },
        radius: 230,
        targetCount: 12,
        riskRating: 0.6,
        classWeights: {
            rockBody: 0.09,
            metalScrap: 0.23,
            compositeJunk: 0.45,
            carbonRichAsteroid: 0.07,
            volatileIceChunk: 0.16,
        },
    },
    {
        id: 'highRiskSalvagePocket',
        label: 'Exo-Fragment Pocket',
        description: 'Unstable high-energy debris pocket with complex salvage mixes.',
        center: { x: -250, y: -52, z: 240 },
        radius: 225,
        targetCount: 10,
        riskRating: 0.77,
        classWeights: {
            rockBody: 0.07,
            metalScrap: 0.2,
            compositeJunk: 0.36,
            carbonRichAsteroid: 0.14,
            volatileIceChunk: 0.23,
        },
    },
];
const marsCorridorZones = [
    {
        id: 'nearStationBelt',
        label: 'Mars Transfer Ring',
        description: 'Lower-risk transfer corridor near the Mars station.',
        center: { x: 0, y: 0, z: 0 },
        radius: 255,
        targetCount: 16,
        riskRating: 0.35,
        classWeights: {
            rockBody: 0.26,
            metalScrap: 0.17,
            compositeJunk: 0.14,
            carbonRichAsteroid: 0.26,
            volatileIceChunk: 0.17,
        },
    },
    {
        id: 'denseDebrisLane',
        label: 'Phobos Wake',
        description: 'Mixed orbital wake with carbonaceous and metallic clusters.',
        center: { x: 200, y: 24, z: -165 },
        radius: 220,
        targetCount: 12,
        riskRating: 0.58,
        classWeights: {
            rockBody: 0.18,
            metalScrap: 0.22,
            compositeJunk: 0.12,
            carbonRichAsteroid: 0.32,
            volatileIceChunk: 0.16,
        },
    },
    {
        id: 'highRiskSalvagePocket',
        label: 'Deimos Shadow Pocket',
        description: 'Volatile high-risk zone with hard rock and deep carbon feeds.',
        center: { x: -240, y: -48, z: 235 },
        radius: 220,
        targetCount: 10,
        riskRating: 0.8,
        classWeights: {
            rockBody: 0.2,
            metalScrap: 0.1,
            compositeJunk: 0.08,
            carbonRichAsteroid: 0.4,
            volatileIceChunk: 0.22,
        },
    },
];
export const sectorCatalog = {
    flightTraining: {
        id: 'flightTraining',
        label: 'Intro Scene',
        description: 'Dedicated onboarding scene for first-flight controls before entering live sectors.',
        stationName: 'Intro Relay',
        worldSeed: 'flight-training-v1',
        celestialPreset: 'earthMoon',
        portalExit: 'earthCorridor',
        cleanupZones: trainingOrbitZones,
        playerSpawnPosition: { x: -120, y: 8, z: -220 },
        playerSpawnYawDegrees: 28.6,
    },
    earthCorridor: {
        id: 'earthCorridor',
        label: 'Earth Corridor',
        description: 'Earth-adjacent cleanup corridor with heavy human-made debris streams.',
        stationName: 'Earth Relay Station',
        worldSeed: 'earth-corridor-v1',
        celestialPreset: 'earthMoon',
        portalExit: 'marsCorridor',
        cleanupZones: earthCorridorZones,
        playerSpawnPosition: { x: -145, y: 12, z: -210 },
        playerSpawnYawDegrees: 34.8,
    },
    marsCorridor: {
        id: 'marsCorridor',
        label: 'Mars Corridor',
        description: 'Mars transfer corridor with carbon-rich bodies and volatile pockets.',
        stationName: 'Mars Transfer Station',
        worldSeed: 'mars-corridor-v1',
        celestialPreset: 'marsMoons',
        portalExit: 'earthCorridor',
        cleanupZones: marsCorridorZones,
        playerSpawnPosition: { x: -112, y: 10, z: -178 },
        playerSpawnYawDegrees: 32.2,
    },
};
export const orderedSectors = [
    sectorCatalog.flightTraining,
    sectorCatalog.earthCorridor,
    sectorCatalog.marsCorridor,
];
const TWO_PI = Math.PI * 2;
const sectorCelestialConfigCatalog = {
    earthCorridor: {
        sunAnchorPosition: { x: -14500, y: 2600, z: -11800 },
        sunLightBaseIntensity: 1.05,
        sunLightPulseAmplitude: 0.08,
        sunLightPulseFrequency: 0.08,
        sunVisualPulseAmplitude: 0.022,
        sunVisualPulseFrequency: 0.12,
        primaryBodyId: 'earth',
        bodies: [
            {
                id: 'sun',
                label: 'Sun',
                material: 'sun',
                renderMode: 'background',
                anchor: 'sun',
                offset: { x: 0, y: 0, z: 0 },
                diameter: 620,
                segments: 28,
                spinRate: 0,
            },
            {
                id: 'mercury',
                label: 'Mercury',
                material: 'mercury',
                renderMode: 'background',
                anchor: 'sun',
                offset: { x: -980, y: -140, z: -320 },
                diameter: 12,
                segments: 18,
                spinRate: TWO_PI / 5_067_014,
                orbit: {
                    periodSeconds: 7_600_531,
                    pitch: 0.122,
                },
            },
            {
                id: 'venus',
                label: 'Venus',
                material: 'venus',
                renderMode: 'background',
                anchor: 'sun',
                offset: { x: -1500, y: -180, z: -500 },
                diameter: 20,
                segments: 20,
                spinRate: -TWO_PI / 20_995_200,
                orbit: {
                    periodSeconds: 19_414_149,
                    pitch: 0.059,
                },
            },
            {
                id: 'earth',
                label: 'Earth',
                material: 'earth',
                renderMode: 'background',
                anchor: 'scene',
                offset: { x: 1900, y: 220, z: -620 },
                diameter: 980,
                segments: 24,
                spinRate: TWO_PI / 86_164,
            },
            {
                id: 'moon',
                label: 'Moon',
                material: 'moon',
                renderMode: 'background',
                anchor: 'primary',
                offset: { x: -5200, y: -220, z: 660 },
                diameter: 270,
                segments: 20,
                spinRate: TWO_PI / 259_200,
                orbit: {
                    periodSeconds: 259_200,
                    pitch: 0.03,
                },
            },
            {
                id: 'mars',
                label: 'Mars',
                material: 'mars',
                renderMode: 'background',
                anchor: 'sun',
                offset: { x: -2200, y: -210, z: -760 },
                diameter: 16,
                segments: 18,
                spinRate: TWO_PI / 88_642,
                orbit: {
                    periodSeconds: 59_355_072,
                    pitch: 0.032,
                },
            },
            {
                id: 'jupiter',
                label: 'Jupiter',
                material: 'jupiter',
                renderMode: 'background',
                anchor: 'sun',
                offset: { x: -3400, y: -150, z: -1100 },
                diameter: 22,
                segments: 24,
                spinRate: TWO_PI / 35_730,
                orbit: {
                    periodSeconds: 374_335_776,
                    pitch: 0.022,
                },
            },
            {
                id: 'saturn',
                label: 'Saturn',
                material: 'saturn',
                renderMode: 'background',
                anchor: 'sun',
                offset: { x: -4300, y: -120, z: -1400 },
                diameter: 20,
                segments: 22,
                spinRate: TWO_PI / 38_520,
                orbit: {
                    periodSeconds: 929_596_608,
                    pitch: 0.043,
                },
            },
            {
                id: 'uranus',
                label: 'Uranus',
                material: 'uranus',
                renderMode: 'background',
                anchor: 'sun',
                offset: { x: -5200, y: -90, z: -1750 },
                diameter: 15,
                segments: 20,
                spinRate: -TWO_PI / 62_064,
                orbit: {
                    periodSeconds: 2_651_846_400,
                    pitch: 0.013,
                },
            },
            {
                id: 'neptune',
                label: 'Neptune',
                material: 'neptune',
                renderMode: 'background',
                anchor: 'sun',
                offset: { x: -6100, y: -70, z: -2100 },
                diameter: 13,
                segments: 20,
                spinRate: TWO_PI / 57_996,
                orbit: {
                    periodSeconds: 5_198_144_000,
                    pitch: 0.031,
                },
            },
            {
                id: 'pluto',
                label: 'Pluto',
                material: 'pluto',
                renderMode: 'background',
                anchor: 'sun',
                offset: { x: -7000, y: -55, z: -2500 },
                diameter: 8,
                segments: 16,
                spinRate: -TWO_PI / 551_856,
                orbit: {
                    periodSeconds: 7_821_887_040,
                    pitch: 0.299,
                },
            },
        ],
    },
    marsCorridor: {
        sunAnchorPosition: { x: -1280, y: 460, z: -980 },
        sunLightBaseIntensity: 1.05,
        sunLightPulseAmplitude: 0.08,
        sunLightPulseFrequency: 0.08,
        sunVisualPulseAmplitude: 0.022,
        sunVisualPulseFrequency: 0.12,
        primaryBodyId: 'mars',
        bodies: [
            {
                id: 'sun',
                label: 'Sun',
                material: 'sun',
                renderMode: 'background',
                anchor: 'scene',
                offset: { x: 0, y: 0, z: 0 },
                diameter: 170,
                segments: 28,
                spinRate: 0,
            },
            {
                id: 'mars',
                label: 'Mars',
                material: 'mars',
                renderMode: 'background',
                anchor: 'sun',
                offset: { x: 420, y: 0, z: 0 },
                diameter: 51,
                segments: 24,
                spinRate: (TWO_PI * 8) / 12400,
                orbit: {
                    periodSeconds: 12400,
                    pitch: 0.08,
                },
            },
            {
                id: 'phobos',
                label: 'Phobos',
                material: 'moon',
                renderMode: 'background',
                anchor: 'primary',
                offset: { x: 48, y: 0, z: 0 },
                diameter: 10,
                segments: 18,
                spinRate: (TWO_PI * 2.4) / 420,
                orbit: {
                    periodSeconds: 420,
                    pitch: 0.18,
                },
            },
            {
                id: 'deimos',
                label: 'Deimos',
                material: 'moon',
                renderMode: 'background',
                anchor: 'primary',
                offset: { x: 82, y: 0, z: 0 },
                diameter: 7,
                segments: 16,
                spinRate: (TWO_PI * 2.2) / 980,
                orbit: {
                    periodSeconds: 980,
                    pitch: -0.12,
                },
            },
        ],
    },
};
export function isSectorId(value) {
    return value === 'flightTraining' || value === 'earthCorridor' || value === 'marsCorridor';
}
export function resolveSectorDefinition(sectorId) {
    if (sectorId && sectorCatalog[sectorId]) {
        return sectorCatalog[sectorId];
    }
    return sectorCatalog[DEFAULT_START_SECTOR_ID];
}
export function resolveSectorWorldTargetCount(sectorId) {
    const sector = resolveSectorDefinition(sectorId);
    return sector.cleanupZones.reduce((sum, zone) => sum + zone.targetCount, 0);
}
export function resolveSectorCelestialConfig(sectorId) {
    if (sectorId === TRAINING_SECTOR_ID) {
        return sectorCelestialConfigCatalog[EARTH_CORRIDOR_SECTOR_ID];
    }
    return sectorCelestialConfigCatalog[sectorId];
}
